'use client';

import { useState } from 'react';
import { Download, FileText, LoaderCircle } from 'lucide-react';
import { Button } from '@/components/ui/button';
import {
  BORDER_SOFT,
  BRAND_DARK,
  MUTED,
  loadBrandLogo,
  randomOwnerPassword,
  sectionBox,
  stampFooterOnAllPages,
} from '@/lib/pdf/brand';

export function AttendanceExportActions({ name, loginId, today }: { name: string; loginId: string; today: string }) {
  const [exportingPdf, setExportingPdf] = useState(false);

  function exportCsv() {
    const csv = [['Field', 'Value'], ['Date', today], ['Staff account', name], ['Staff ID', loginId]]
      .map((row) => row.map((value) => `"${value.replaceAll('"', '""')}"`).join(','))
      .join('\n');
    const url = URL.createObjectURL(new Blob([csv], { type: 'text/csv;charset=utf-8' }));
    const anchor = document.createElement('a');
    anchor.href = url;
    anchor.download = `safawala-attendance-${new Date().toISOString().slice(0, 10)}.csv`;
    anchor.click();
    URL.revokeObjectURL(url);
  }

  async function exportPdf() {
    setExportingPdf(true);
    try {
      const [{ jsPDF }, logo] = await Promise.all([import('jspdf'), loadBrandLogo()]);
      const doc = new jsPDF({
        unit: 'mm',
        format: 'a4',
        encryption: { userPassword: '', ownerPassword: randomOwnerPassword(), userPermissions: ['print', 'copy'] },
      });
      const width = doc.internal.pageSize.getWidth();
      const left = 16;
      const right = width - 16;
      const boxWidth = right - left;

      // ---- Header banner ----
      const headerTop = 10;
      const headerHeight = 30;
      doc.setFillColor(255, 255, 255);
      doc.setDrawColor(...BORDER_SOFT);
      doc.setLineWidth(0.45);
      doc.roundedRect(left - 6, headerTop, boxWidth + 12, headerHeight, 3, 3, 'FD');
      if (logo) {
        const logoH = 12;
        doc.addImage(logo.dataUrl, 'PNG', left, headerTop + 5, logoH * logo.ratio, logoH);
      } else {
        doc.setTextColor(...BRAND_DARK);
        doc.setFont('helvetica', 'bold');
        doc.setFontSize(16);
        doc.text('SAFAWALA', left, headerTop + 13);
      }
      doc.setTextColor(...MUTED);
      doc.setFont('helvetica', 'normal');
      doc.setFontSize(7.5);
      doc.text('Premium Wedding Accessories', left, headerTop + headerHeight - 4);
      doc.setTextColor(...BRAND_DARK);
      doc.setFont('helvetica', 'bold');
      doc.setFontSize(12);
      doc.text(loginId, right, headerTop + 10, { align: 'right' });
      doc.setFontSize(8.5);
      doc.setFont('helvetica', 'normal');
      doc.text('ATTENDANCE STATUS', right, headerTop + 17, { align: 'right' });
      doc.setFontSize(7.5);
      doc.setTextColor(...MUTED);
      doc.text(today, right, headerTop + 23, { align: 'right' });

      // ---- Staff info box ----
      let y = headerTop + headerHeight + 8;
      const boxH = 26;
      sectionBox(doc, left, y, boxWidth, boxH);
      let by = y + 8;
      doc.setFont('helvetica', 'bold');
      doc.setFontSize(9);
      doc.setTextColor(...BRAND_DARK);
      doc.text('STAFF ACCOUNT', left + 5, by);
      by += 5.5;
      doc.setFontSize(9.5);
      doc.text(name, left + 5, by);
      by += 4.6;
      doc.setFont('helvetica', 'normal');
      doc.setFontSize(9);
      doc.setTextColor(...MUTED);
      doc.text(`Staff ID: ${loginId}`, left + 5, by);
      by += 4.6;
      doc.text('Attendance module access is active for this account.', left + 5, by);
      y += boxH + 8;

      doc.setFont('helvetica', 'normal');
      doc.setFontSize(9);
      doc.setTextColor(...BRAND_DARK);
      doc.text(`Status recorded on ${today}.`, left, y);

      stampFooterOnAllPages(doc, { left, right, note: 'Generated by Safawala Staff Portal.' });
      doc.save(`safawala-attendance-${new Date().toISOString().slice(0, 10)}.pdf`);
    } finally {
      setExportingPdf(false);
    }
  }

  return (
    <div className="flex flex-wrap gap-2">
      <Button variant="outline" onClick={exportCsv}>
        <Download />
        CSV
      </Button>
      <Button variant="outline" onClick={exportPdf} disabled={exportingPdf}>
        {exportingPdf ? <LoaderCircle className="animate-spin" /> : <FileText />}
        PDF
      </Button>
    </div>
  );
}
