'use client';

import { useState, type ReactNode } from 'react';
import { CalendarDays, LockKeyhole, Plus, RefreshCw, Search } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Badge } from '@/components/ui/badge';
import { Card, CardContent } from '@/components/ui/card';
import { DashboardHeader } from '@/components/layout/dashboard-header';
import { createLeadAction, createLockedDateAction, deleteLockedDateAction } from '@/app/leads/actions';

type Lead = { id: number; full_name: string; phone: string; email: string | null; event_date: string; location: string | null; package_interest: string | null; source: string; status: string; requirements: string | null; assigned_staff_id: number | null };
type LockedDate = { id: number; locked_date: string; label: string; notes: string | null };
type Staff = { id: number; name: string };
const statusTone: Record<string, string> = { new: 'border-blue-200 bg-blue-50 text-blue-700', contacted: 'border-amber-200 bg-amber-50 text-amber-700', interested: 'border-violet-200 bg-violet-50 text-violet-700', converted: 'border-emerald-200 bg-emerald-50 text-emerald-700', lost: 'border-red-200 bg-red-50 text-red-700' };
const leadSources = ['Website', 'Instagram', 'Facebook', 'Google Search', 'Walk-in', 'Referral', 'Manual Entry', 'Other'];

export function LeadsCenter({ leads, lockedDates, staff, loadError = '' }: { leads: Lead[]; lockedDates: LockedDate[]; staff: Staff[]; loadError?: string }) {
  const [modal, setModal] = useState<'lead' | 'locked' | null>(null);
  const [actionError, setActionError] = useState('');
  const [query, setQuery] = useState('');
  const [source, setSource] = useState('all');
  const filtered = leads.filter((lead) => `${lead.full_name} ${lead.phone} ${lead.location ?? ''}`.toLowerCase().includes(query.toLowerCase()) && (source === 'all' || lead.source === source));
  const counts = (value: string) => leads.filter((lead) => lead.status === value).length;
  return <div className="space-y-5">
    {actionError ? <Card className="border-red-200 bg-red-50 text-red-700 shadow-level-1"><CardContent className="p-4 text-sm">{actionError}</CardContent></Card> : null}
    {loadError && !actionError ? <Card className="border-red-200 bg-red-50 text-red-700 shadow-level-1"><CardContent className="p-4 text-sm"><p className="font-semibold">Leads database setup is incomplete</p><p className="mt-1">Apply the Railway database schema before creating leads. Details: {loadError}</p></CardContent></Card> : null}
    <DashboardHeader title="Leads Center" subtitle="Track package enquiries, manage manual leads, and follow up." backHref="/dashboard" actions={<><Button variant="outline" size="sm"><RefreshCw className="size-4" /> Refresh</Button><Button variant="outline" size="sm" onClick={() => setModal('locked')}><LockKeyhole className="size-4" /> Lock Date{lockedDates.length ? ` (${lockedDates.length})` : ''}</Button><Button size="sm" onClick={() => setModal('lead')}><Plus className="size-4" /> Add Lead</Button></>} />
    <div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-5">{[['new','New'],['contacted','Contacted'],['interested','Interested'],['converted','Converted'],['lost','Lost']].map(([key,label]) => <Card key={key} className="border-border shadow-level-1"><CardContent className="p-4"><p className="text-xs uppercase tracking-wide text-muted-foreground">{label}</p><p className="mt-2 text-2xl font-semibold">{counts(key)}</p></CardContent></Card>)}</div>
    <Card className="border-border shadow-level-1"><CardContent className="flex flex-wrap items-center gap-3 p-4"><div className="relative min-w-[240px] flex-1"><Search className="absolute left-3 top-1/2 size-4 -translate-y-1/2 text-muted-foreground" /><input value={query} onChange={(e) => setQuery(e.target.value)} placeholder="Search by name, WhatsApp, location…" className="h-10 w-full rounded-lg border border-input bg-white pl-9 pr-3 text-sm outline-none focus:border-ring dark:bg-card" /></div><select value={source} onChange={(e) => setSource(e.target.value)} className="h-10 rounded-lg border border-input bg-white px-3 text-sm dark:bg-card"><option value="all">All Sources</option>{leadSources.map((item) => <option key={item}>{item}</option>)}</select></CardContent></Card>
    <Card className="overflow-hidden border-border shadow-level-1"><CardContent className="p-0"><div className="overflow-x-auto"><table className="w-full min-w-[760px] text-left text-sm"><thead className="border-b bg-[#faf8f4] text-xs uppercase tracking-wide text-muted-foreground"><tr><th className="px-5 py-3">Lead details</th><th className="px-5 py-3">Event date</th><th className="px-5 py-3">Source</th><th className="px-5 py-3">Status</th><th className="px-5 py-3">Package / requirements</th></tr></thead><tbody>{filtered.map((lead) => <tr key={lead.id} className="border-b last:border-0"><td className="px-5 py-4"><p className="font-semibold">{lead.full_name}</p><p className="text-xs text-muted-foreground">{lead.phone}{lead.email ? ` · ${lead.email}` : ''}</p><p className="mt-1 text-xs text-muted-foreground">{lead.location || 'Location not added'}</p></td><td className="px-5 py-4 text-xs text-muted-foreground"><CalendarDays className="mr-1 inline size-3.5" />{lead.event_date}</td><td className="px-5 py-4"><Badge variant="outline">{lead.source}</Badge></td><td className="px-5 py-4"><Badge variant="outline" className={statusTone[lead.status] ?? ''}>{lead.status}</Badge></td><td className="max-w-[260px] px-5 py-4 text-xs text-muted-foreground">{lead.package_interest || '—'}{lead.requirements ? ` · ${lead.requirements}` : ''}</td></tr>)}</tbody></table>{!filtered.length ? <p className="p-10 text-center text-sm text-muted-foreground">No leads match your filters.</p> : null}</div></CardContent></Card>
    {modal === 'lead' ? <Modal title="Add New Lead Manually" close={() => setModal(null)}><form action={async (data) => { try { await createLeadAction(data); setModal(null); setActionError(''); } catch (error) { setActionError(error instanceof Error ? error.message : 'Unable to save lead.'); } }} className="grid gap-3 sm:grid-cols-2"><Field label="Full Name *" name="full_name" required /><Field label="WhatsApp / Phone *" name="phone" required pattern="[0-9]{10}" maxLength={10} inputMode="numeric" /><Field label="Email Address" name="email" type="email" /><Field label="Event Date *" name="event_date" type="date" required /><Field label="Location" name="location" /><Field label="Package Interest" name="package_interest" /><label className="text-sm">Lead Source<select name="source" className="mt-1 h-10 w-full rounded-lg border px-3"><option>Manual Entry</option><option>Website</option><option>Instagram</option><option>Facebook</option><option>Google Search</option><option>Walk-in</option><option>Referral</option><option>Other</option></select></label><label className="text-sm">Initial Status<select name="status" className="mt-1 h-10 w-full rounded-lg border px-3"><option value="new">New</option><option value="contacted">Contacted</option><option value="interested">Interested</option></select></label><label className="text-sm sm:col-span-2">Assigned Staff<select name="assigned_staff_id" className="mt-1 h-10 w-full rounded-lg border px-3"><option value="">Select follow-up staff</option>{staff.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select></label><Field label="Requirements Box" name="requirements" area /><Field label="Internal Notes" name="internal_notes" area /><div className="flex justify-end gap-2 sm:col-span-2"><Button type="button" variant="outline" onClick={() => setModal(null)}>Cancel</Button><Button type="submit">Create Lead</Button></div></form></Modal> : null}
    {modal === 'locked' ? <Modal title="Locked Dates" close={() => setModal(null)}><div className="space-y-4"><form action={async (data) => { try { await createLockedDateAction(data); setModal(null); setActionError(''); } catch (error) { setActionError(error instanceof Error ? error.message : 'Unable to lock date.'); } }} className="grid gap-3 sm:grid-cols-2"><Field label="Date *" name="locked_date" type="date" required /><Field label="Label *" name="label" placeholder="Holiday, private event…" required /><Field label="Notes" name="notes" area /><div className="flex items-end"><Button type="submit"><Plus className="size-4" /> Lock Date</Button></div></form><div className="divide-y rounded-lg border">{lockedDates.map((item) => <div key={item.id} className="flex items-center justify-between gap-3 p-3 text-sm"><div><p className="font-medium">{item.label}</p><p className="text-xs text-muted-foreground">{item.locked_date}{item.notes ? ` · ${item.notes}` : ''}</p></div><form action={deleteLockedDateAction}><input type="hidden" name="id" value={item.id} /><Button type="submit" variant="ghost" size="sm">Remove</Button></form></div>)}{!lockedDates.length ? <p className="p-6 text-center text-sm text-muted-foreground">No upcoming locked dates.</p> : null}</div></div></Modal> : null}
  </div>;
}
function Field({ label, name, type = 'text', required, placeholder, area, pattern, maxLength, inputMode }: { label: string; name: string; type?: string; required?: boolean; placeholder?: string; area?: boolean; pattern?: string; maxLength?: number; inputMode?: 'numeric' | 'text' }) { return <label className="text-sm">{label}{area ? <textarea name={name} required={required} placeholder={placeholder} className="mt-1 min-h-20 w-full rounded-lg border px-3 py-2" /> : <input name={name} type={type} required={required} pattern={pattern} maxLength={maxLength} inputMode={inputMode} placeholder={placeholder} className="mt-1 h-10 w-full rounded-lg border px-3" />}</label>; }
function Modal({ title, close, children }: { title: string; close: () => void; children: ReactNode }) { return <div className="fixed inset-0 z-50 grid place-items-center bg-black/35 p-4"><Card className="max-h-[90vh] w-full max-w-2xl overflow-y-auto shadow-level-3"><CardContent className="p-5"><div className="mb-5 flex items-start justify-between"><div><h2 className="text-xl font-semibold">{title}</h2><p className="mt-1 text-sm text-muted-foreground">Create and manage CRM follow-up data.</p></div><Button type="button" variant="ghost" size="sm" onClick={close}>×</Button></div>{children}</CardContent></Card></div>; }
